### ISSUE TITLE
Make use of tests from BLS standard when released.

### ISSUE THREAD

**Issue by CarlBeek** [CarlBeek/eth2.0-deposit-tooling#10]
When the tests for BLS12-381 are released via the standardisation efforts, transition tests to use those tests where possible.

This is possible in:

- [ ] `hkdf_mod_r` tests can be lifted from `KeyGen` in standard

**Comment by austinabell** [comment]
Is this why these tests: https://github.com/CarlBeek/eth2.0-deposit-tooling/blob/master/tests/test_key_derivation/test_vectors/tree_kdf.json don't match the current spec? All but one of the vectors in the rust impl pass and I was trying to check where the issue is
